# Generated by Django 4.1 on 2023-11-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_postblog_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='url',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
