# Generated by Django 4.1 on 2023-12-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_accent_author_level_topic_movie_episodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodes',
            name='episodes',
            field=models.ManyToManyField(related_name='episode_related', to='main.movie', verbose_name='Эпизод'),
        ),
    ]
