# Generated by Django 4.1 on 2023-12-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_episodes_episodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('number_epis', models.PositiveSmallIntegerField(verbose_name='Номер эпизода')),
                ('url', models.SlugField(verbose_name='Ссылка')),
                ('video', models.FileField(upload_to='', verbose_name='Видео')),
                ('accent', models.ManyToManyField(related_name='accent_related', to='main.accent', verbose_name='Акцент')),
                ('author', models.ManyToManyField(related_name='author_related', to='main.author', verbose_name='Автор')),
                ('level', models.ManyToManyField(related_name='lvl_related', to='main.level', verbose_name='Уровень')),
                ('topic', models.ManyToManyField(related_name='topic_related', to='main.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Эпизод',
                'verbose_name_plural': 'Эпизоды',
            },
        ),
        migrations.RemoveField(
            model_name='movie',
            name='accent',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='author',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='level',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='url',
        ),
        migrations.DeleteModel(
            name='Episodes',
        ),
        migrations.AddField(
            model_name='movie',
            name='episodes',
            field=models.ManyToManyField(related_name='ep_related', to='main.episode', verbose_name='Эпизод'),
        ),
    ]
