# Generated by Django 4.1 on 2024-01-23 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_vocabulary_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='Вопрос')),
                ('first', models.CharField(max_length=100, verbose_name='Первый ответ')),
                ('second', models.CharField(max_length=100, verbose_name='Второй ответ')),
                ('third', models.CharField(max_length=100, verbose_name='Третий ответ')),
                ('episode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.episode')),
            ],
        ),
    ]
