# Generated by Django 4.1 on 2024-08-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_testcinema_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='script',
            field=models.TextField(default=str, verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
