# Generated by Django 4.1 on 2025-01-24 15:48

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=100, unique=True, verbose_name='Логин')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=100, unique=True, verbose_name='Логин')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('code', models.CharField(max_length=100, verbose_name='Код')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=100, unique=True, verbose_name='Логин')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('held', 'Проведен'), ('cancaled', 'Отмена')], max_length=15)),
                ('payed', models.CharField(choices=[('payed', 'Оплачен'), ('notpayed', 'Не оплачен')], max_length=15)),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Причина отмены')),
                ('student', models.ManyToManyField(related_name='student_related', to='main.student', verbose_name='Студент')),
                ('teacher', models.ManyToManyField(related_name='teacher_related', to='main.teacher', verbose_name='Преподаватель')),
            ],
        ),
    ]
