# Generated by Django 4.1 on 2025-01-30 11:45

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_accent_author_discusboard_episode_level_movie_and_more'),
    ]

    operations = [
       
    ]
