# Generated by Django 4.1 on 2023-12-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_postblog_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accent', models.CharField(max_length=100, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Акцент',
                'verbose_name_plural': 'Акценты',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('url', models.URLField(verbose_name='Ссылка на страницу')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10, verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название фильма')),
                ('url', models.SlugField(unique=True)),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('accent', models.ManyToManyField(related_name='accent_related', to='main.accent', verbose_name='Акцент')),
                ('author', models.ManyToManyField(related_name='author_related', to='main.author', verbose_name='Автор')),
                ('level', models.ManyToManyField(related_name='level_related', to='main.level', verbose_name='Уровень')),
                ('topic', models.ManyToManyField(related_name='topic_related', to='main.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название фильма')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('episodes', models.ManyToManyField(related_name='episode', to='main.movie', verbose_name='Эпизод')),
            ],
            options={
                'verbose_name': 'Эпизод',
                'verbose_name_plural': 'Эпизоды',
            },
        ),
    ]
