# Generated by Django 4.1 on 2024-01-08 17:38

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_test_frntest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='text',
        ),
        migrations.AddField(
            model_name='test',
            name='t',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), default=1, max_length=66, size=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FrnTest',
        ),
    ]
