# Generated by Django 4.1 on 2024-01-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_testcinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcinema',
            name='correct',
            field=models.SmallIntegerField(default=1, verbose_name='Правильный ответ'),
            preserve_default=False,
        ),
    ]
