# Generated by Django 4.1 on 2025-02-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_student_teacher_alter_lessons_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
