# Generated by Django 4.1 on 2025-02-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_student_city_student_contacts_student_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_point',
            field=models.TextField(blank=True, null=True, verbose_name='Сейчас'),
        ),
    ]
