# Generated by Django 4.1 on 2025-02-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_student_city_alter_student_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Код ученика')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='code',
        ),
        migrations.AddField(
            model_name='student',
            name='code',
            field=models.ManyToManyField(related_name='student_code', to='crm.studentscode', verbose_name='Код ученика'),
        ),
    ]
