# Generated by Django 4.1 on 2025-02-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_studentscode_remove_student_code_student_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.AddField(
            model_name='studentscode',
            name='teacher',
            field=models.ManyToManyField(related_name='teacher_related_stud', to='crm.teacher', verbose_name='Учитель'),
        ),
    ]
